### ISSUE TITLE
Demos do not work on iOS or Android Browsers

### ISSUE THREAD

**Issue by acastro** [googleads/googleads-ima-html5#19]
The simple and advanced samples do not load correctly on some mobile devices, causing the play button to not appear.  Playback seems unaffected on desktop browsers.

**Comment by shawnbuso** [comment]
Can you give some examples of specific devices on which you're seeing problems? Thanks!

**Comment by acastro** [comment]
Not Working: iOS 9.1,9.2,9.3 (iphone 6)
Working: iOS 8.1 (iphone 6)

**Comment by acastro** [comment]
iOS 9.3.1 seems to work now on my physical device, but the buttons were not clickable before

**Comment by shawnbuso** [comment]
The advanced and playlist samples are expected to not work on iPhone - iOS puts an overlay on top of video players on iPhones that steals clicks, so when you try to click the play button that overlay will get the click instead of the button. The simple sample should work though if you click our blue play button - are you still seeing an issue there? I tested on an iOS 9.3 iPhone simulator and it did work for me.
