### ISSUE TITLE
AUTOPLAY exception not getting caught

### ISSUE THREAD

**Issue by 580** [googleads/googleads-ima-html5#29]
Dear googleads-ima html5 team, 

From the [release notes](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/history), it reads:
|3.186.1 | 12/7/2017 | AdErrorEvent.getInnerError() may now return an inner AdError object. This allows checking to see if autoplay failed.|

I created a codepen to have a try on this, but I can't see an autoplay issue get caught, the codepen link is: [https://codepen.io/anon/pen/ppWOPN ](https://codepen.io/anon/pen/ppWOPN ). 

I am using **Chrome v63**, with [autoplay policy](chrome://flags/#autoplay-policy) set to "Document User Activation is Required". (For what I am seeing is that the player is freezing on the first frame of the video ad, but no adError message from web console )

Is there anything I've missed? 

Thanks,
Iries

**Comment by shawnbuso** [comment]
Hi there,

This issue tracker is for bugs and feature requests in the sample code provided in the repo. It sounds like this issue is particular to your implementation. Could you reach out to our support team on our [forum](https://groups.google.com/forum/#!forum/ima-sdk)? They'll be able to give you better assistance there.

Thanks!
Shawn

**Comment by 580** [comment]
Thank you, Shawn. I'll move the question to the forum.
