### ISSUE TITLE
Banner not displayed but tracking URLs called

### ISSUE THREAD

**Issue by dani9del9** [googleads/googleads-ima-html5#36]
Hello, I have this issue.

I have a VAST like this:
[https://cmod592.live.streamtheworld.com/ondemand/ars?type=preroll&fmt=vast&banners=none&stid=109863&version=1.6.1&gdpr=1&gdpr_consent=123456](https://cmod592.live.streamtheworld.com/ondemand/ars?type=preroll&fmt=vast&banners=none&stid=109863&version=1.6.1&gdpr=1&gdpr_consent=123456
)

I don't want to display banners but IMA automatically calls every confirmation URL although banners are not displayed

Here you are a test page:
[http://innovacion.prisadigital.com/psdmedia/media/top/tests/SUPERTEST.html?idplayer=267&otros=&idcuenta=playser&idmedia=cadenaser_carruseldeportivo_20141130_200000_210000&tplib_=on&mediatype=audio&keepalive=0&mmbase_=on&dev=false&entorno=des&ocultar=true&tap=1](http://innovacion.prisadigital.com/psdmedia/media/top/tests/SUPERTEST.html?idplayer=267&otros=&idcuenta=playser&idmedia=cadenaser_carruseldeportivo_20141130_200000_210000&tplib_=on&mediatype=audio&keepalive=0&mmbase_=on&dev=false&entorno=des&ocultar=true&tap=1)

**Comment by Kiro705** [comment]
Hello @dani9del9 ,

Is this issue still reproducible? I attempted to reproduce it using your VAST tag, but it returned an empty VAST response.

If this is still reproducible, I recommend reaching out on the [IMA technical forum](https://groups.google.com/g/ima-sdk/), since this issue is not specific to these sample apps.

Please feel free to reopen this issue if you have any questions.
