### ISSUE TITLE
Sample not working with Adsense for games (AFG) tag

### ISSUE THREAD

**Issue by binoculars88** [googleads/googleads-ima-html5#43]
I'm trying to integrate the HTLM5 IMA SDK in my game launcher as described [here](https://support.google.com/adsense/troubleshooter/6058591?visit_id=637066629506832641-3514154238&rd=1#ts=6058657%2C6058546%2C6058687%2C6058675).

I use the [simple sample](https://github.com/googleads/googleads-ima-html5/tree/master/simple) to get started. This sample works perfectly with the tag provided in the sample, however, when I use the tag for games mentioned in the Adsense for Games support doc, I get:
`{l: "Unable to request ads from server due to network error.", h: 1012, o: "adLoadError"}`

Here's the tag that should be used for games to get approved:
`https://googleads.g.doubleclick.net/pagead/ads?ad_type=video&client=ca-games-pub-4968145218643279&videoad_start_delay=0&description_url=http%3A%2F%2Fwww.google.com&max_ad_duration=20000&adtest=on`

I also noticed that this tag also doesn't work on VAST testers like [Vast Inspector](https://www.vastinspector.com/). It does seem to work in [Google's inspector](https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector).

Anyone knows what's causing this issue, and how to resolve this?
Thanks a lot in advance!

**Comment by Kiro705** [comment]
Hello @binoculars88 ,

I was able to test your ad using the Advanced sample ([hosted here](https://googleads.github.io/googleads-ima-html5/advanced/)) and was able to see the ad play successfully.

Please feel free to reopen this if you are still able to reproduce the issue, with steps to reproduce included. Also if you think the issue is not specific to the IMA H5 sample, but applies more generally to the IMA SDK, I recommend posting this issue on the [IMA technical forum](https://groups.google.com/g/ima-sdk/).
