### ISSUE TITLE
adblock detection

### ISSUE THREAD

**Issue by supersh86** [googleads/googleads-ima-html5#46]
Hi, apps that block ads are popular right now.
It would be great if google ima could detect a blocking error.
Now I have to make double requests to vast to check whether the user can load you or not.
I use a similar example as in the solution here.
https://stackoverflow.com/questions/40527328/is-it-possible-to-catch-neterr-blocked-by-client

It would be great if an event appeared on Google Ima that detected an ad block.

**Comment by rafa8626** [comment]
@supersh86 I know there’s a way to see this only in debug mode, but I don’t know if it’s being sent as an error.Still investigating

**Comment by Kiro705** [comment]
Hello all,

Since this issue in not specific to the IMA samples, I would recommend raising the issue on the [IMA technical forum](https://groups.google.com/g/ima-sdk/). I think having the IMA check whether ads are blocked and responding in a specific way would be very useful. The technical forum is the place to make that request.

Please feel free to reopen this issue if you have any follow-up questions.
