### ISSUE TITLE
AdDisplayContainer stuck in endless update - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by FrancescoMussi** [googleads/googleads-ima-html5#47]
I have an issue with the google IMA sdk.

It seems the `adDisplayContainer` it's stuck an endless update loop.

```
this.adDisplayContainer = new google.ima.AdDisplayContainer(
          this.$refs.adContainer, this.videoContent);
```

When I watch the `AdDisplayContainer` I get the following error:

`Maximum call stack size exceeded`

I have reproduced the issue in this JSFiddle:
https://jsfiddle.net/fraMussi/53f6vbjh/7/

And made a question on StackOverflow:
https://stackoverflow.com/questions/61640725/maximum-call-stack-size-exceeded-with-vue-google-ima-sdk

Could you be so kind to have a look?

**Comment by Kiro705** [comment]
Hello @FrancescoMussi ,

Since this issue is not specific to the IMA HTML5 sample, I would recommend raising the issue on the [IMA technical forum](https://groups.google.com/g/ima-sdk/).

I am unfamiliar with Vue, but could you explain the need for watching the adDisplayContainer? There may be other IMA methods you can use to accomplish the same thing.
